elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
  volumes:
   - ./config/elasticsearch/config:/usr/share/elasticsearch/config
   - ./config/elasticsearch/data:/usr/share/elasticsearch/data
   - ./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  restart: always

kibana:
  image: kibana
  ports:
   - "5601:5601"
  links:
    - elasticsearch:elasticsearch
  restart: always

logstash:
  image: logstash
  ports:
    - "8080:8080"
  links:
    - elasticsearch:elasticsearch
  restart: always
  volumes:
   - ./config/logstash:/etc/logstash
  command: "logstash -f /etc/logstash"

puller:
  build: logstash-custom-puller
  restart: always
  links:
   - logstash:logstash
  environment:
   SRV_PREFIX: 'http://datafactory.foxites.com/'
   SRV_FILTER: 'mam'
   SRV_FOLDER: 'foxsports-la/xml'
   DEST_PATH: 'df/mam'
